### ISSUE TITLE
Request new CLIJ2_paste3D function

### ISSUE THREAD

**Issue by bvernay** [clij/clij2#16]
Hi Robert,

I hope this message find you well. A member of my team, Marcel Boeglin, has been playing with CLIJ and has asked me to forward his request. Also attached two macros: 1- CPU processing, 2- CLIJ processing with requested new CLIJ function on line 123. He wanted to use CLIJ2_paste3D to process a stack in the GPU and then pull it on the CPU but the result cannot be currently pulled into an existing CPU stack.

Marcel is wondering if it will be possible to create a function like:
Ext.CLIJ2_pull(GPU_Image3D, CPU_ImageStack_ID, Number_Offset)
 - where offset is the slice from which to copy GPU_image3D into CPU_ImageStack
 - where CPU_ImageStack_ID is the image ID of CPU_ImageStack created in ImageJ with the correct width, height and bitdepth.
 
Best wishes

Bertrand

[ImageJ_ExtractRegion3D_toHyperstack_02.txt](https://github.com/clij/clij2/files/4702122/ImageJ_ExtractRegion3D_toHyperstack_02.txt)
[ImageJ_ExtractRegion3D_toHyperstack_02_CLIJ2annotations.txt](https://github.com/clij/clij2/files/4702123/ImageJ_ExtractRegion3D_toHyperstack_02_CLIJ2annotations.txt)

**Comment by haesleinhuepf** [comment]
Hey Bertrand @bvernay ,

that makes a lot of sense! If you promise to test it before June 13th (CLIJ2 release date), I promise to make it before June 6th ;-)

Cheers,
Robert

**Comment by bvernay** [comment]
ready to test now :-)

**Comment by haesleinhuepf** [comment]
Hey Betrand @bvernay ,

alright. Thanks for the very valuable suggestion! This makes a lot of sense indeed.

I added `pullToCurrentSlice` as counterpart of `pushCurrentSlice` and `pullToCurrentSliceSelection` as counterpart of `pushCurrentSliceSelection` They will work like this:

```
// Get test data
run("T1 Head (2.4M, 16-bits)");
input = getTitle();
getDimensions(width, height, channels, slices, frames);

makeRectangle(100, 100, 50, 50);


// Init GPU
run("CLIJ2 Macro Extensions", "cl_device=");
Ext.CLIJ2_clear();

// blur all slices with different sigmas
for(z = 64; z < slices; z++) {
	Stack.setSlice(z + 1);
	
	// push current selection
	Ext.CLIJ2_pushCurrentSliceSelection(input);

	// process it
	Ext.CLIJ2_gaussianBlur2D(input, blurred, z-64, z-64);

	// pull it back 
	Ext.CLIJ2_pullToCurrentSliceSelection(blurred, input);
}

Stack.setSlice(64);
```

It's not exactly what you requested, but almost. But in thay way it fits well in the nomenclature of CLIJ2. It will be available in Fiji starting Tuesday June 2nd. Let me know if you can use it for your purpose!

Have a nice weekend and send greetings to Marcel!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Hey Betrand @bvernay ,

I just updated clij2 on its Fiji update. Thus, you guys can test the new functions now.

Let me know if it works!

Cheers,
Robert

**Comment by bvernay** [comment]
Hi Robert,

Functions tested and they worked but unfortunately not in our context. 

Macro attached. The file t1-Head.zip does need to be copied into the Fiji.App/samples folder
As the log show GPU is 3.5 slower than CPU on my laptop because of the continuous push-pull for each slice.
We probably need to push the whole hyperstacks in the GPU (tricky with some data size) or a subset to be efficient.
[ExtractRegions3D_toHyperstacks_CLIJ2pullToCurrentSlice.txt](https://github.com/clij/clij2/files/4735273/ExtractRegions3D_toHyperstacks_CLIJ2pullToCurrentSlice.txt)
[ExtractRegions3D_toHyperstacks_CLIJ2pullToCurrentSlice.txt](https://github.com/clij/clij2/files/4735277/ExtractRegions3D_toHyperstacks_CLIJ2pullToCurrentSlice.txt)



*** Start Log ***
ExtractRegions3D_toHyperstacks_CLIJ2pullToCurrentSlice.ijm
Copy from CPU intput stack to CPU hyperstack: 763 ms
pullToCurrentSlice(GPU_image2D, CPU_image3D): 2722 ms
GPU process time / CPU process time: 3.5675
*** End log ***

Thank you very much for being so reactive.

Bertrand and Marcel
