### ISSUE TITLE
API-bug with OnlyZeroOverwriteMaximumBox

### ISSUE THREAD

**Issue by haesleinhuepf** [clij/clij2#23]
As @NicoKiaru reported on the forum, the API for OnlyZeroOverwriteMaximumBox has the wrong parameters compared to its macro interface:

https://forum.image.sc/t/clij-dilate-binary/35231/9

This might also be the issue for NonZeroOverwriteMaximum and friends.

**Comment by haesleinhuepf** [comment]
Hey @NicoKiaru,

I just uploaded a hotfix (CLIJ2 2.2.0.7) to maven and the ImageJ update site. The expected API function should be available now:
![image](https://user-images.githubusercontent.com/12660498/98538624-56621880-228b-11eb-8613-94ef1b9e1052.png)

Would you mind cross-checking? 

Thanks!

Cheers,
Robert

**Comment by NicoKiaru** [comment]
On Maven scijava clij2 max version is 2.2.0.0 (https://maven.scijava.org/#nexus-search;quick~clij)

On bintray it's 2.2.0.1 (http://dl.bintray.com/haesleinhuepf/clij/net/haesleinhuepf/clij2_/)

Are you sure 2.2.0.7 is accessible somewhere ?
