### ISSUE TITLE
CL_MEM_OBJECT_ALLOCATION_FAILURE on laptop with integrated AND dedicated graphics

### ISSUE THREAD

**Issue by krizzodil** [clij/clij2#28]
[clij_problem_exception.txt](https://github.com/clij/clij2/files/5695252/clij_problem_exception.txt)
[clij_problem_info.txt](https://github.com/clij/clij2/files/5695253/clij_problem_info.txt)
[clij_problem.csv.txt](https://github.com/clij/clij2/files/5695255/clij_problem.csv.txt)

![clij_problem](https://user-images.githubusercontent.com/63590534/102203197-92ab1900-3ec8-11eb-9e20-7b22d5015c25.PNG)

Hello!

I'm experiencing an issue with, i guess, GPU RAM usage. 
I tried to run a clij2 gaussian filter, radius x30y30 on a rather large stack of approx 2359x2363x163 16 bit, 1.7GB, but got an OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE

It might be because I'm running a gaming laptop with, both, an integrated GPU, and a dedicated GPU. Maybe clij gets confused by the readouts.
It's an Asus TUF FX705 with an AMD Ryzen 7 3750H and an NVidia GeForce GTX 1660 Ti 6 GB GDDR6.

I tried to include all the information in the screenshot, but forgot the clij versions. I installed it today via FIJI update sites:
clij  1.7.5.1
clij2 2.2.0.11
clijx 0.30.1.0
ImageJ 1.53c

I can easily reproduce the error, in case you need more information.

Thank you!
Christian

p.s.: CLIJ is crazy! I'm also looking forward to clesperanto, especially for Python! I'm still trying to make the prototype work on my computer (edit: It works now! It's nice :) ).

edit: Now with text-files

**Comment by haesleinhuepf** [comment]
Hi @krizzodil ,

I'm glad to hear you enjoy using clij. :-) 

When working with large images and large kernel on Windows, it's possible that the operating system kills operations before they finish. Windows is afraid that the GPU is in an endless loop and stops execution. In order to increase the timeout, please follow the instructions on this site:
https://clij.github.io/clij2-docs/troubleshooting

Let me know if this solves the issue!

Best,
Robert

**Comment by krizzodil** [comment]
![clij_problem_2](https://user-images.githubusercontent.com/63590534/102499883-ffb2e000-407b-11eb-8e42-789aef7b3fb3.PNG)

Hello @haesleinhuepf !

I've now followed the first entry, "Big Images on NVidia graphics cards", and tried again, after restarting my computer. The problem persists. I also tried a higher value (ac), with the same outcome. 
Do expect that the clijx RAM monitor displays over-occupancy?
I'm actually not sure if I am reporting an issue, or something expected with large images.

In Python I get a similar (same?) error using cle.gaussian_blur. In short:
  File "<generated code>", line 90, in enqueue_knl_gaussian_blur_separable_3d
  pyopencl._cl.MemoryError: clEnqueueNDRangeKernel failed: MEM_OBJECT_ALLOCATION_FAILURE
I just solved it by separating the stack into chunks using numpy.split() and processing them one after the other. Of course, this would also be an option in FIJI, though a bit awkward.

Best wishes,
Christian

**Comment by haesleinhuepf** [comment]
Hi Christian @krizzodil ,

I think I can see the issue. Please execute the [clinfo macro](https://github.com/clij/clij2-docs/blob/master/src/main/macro/clInfo.ijm) to determine the capabilities of your GPU:

![image](https://user-images.githubusercontent.com/12660498/102528339-b1fb9f00-409e-11eb-9565-964b7df47ca0.png)

You can read in the line "MaxMemoryAllocationSizeInBytes" how large an image can be. This value depends on the vendor / model / driver and is typically a quarter of the GPU memory. Thus, your image is something like 100 MB too large. Consider cropping the image. Alternatively, working with an 8-bit image of the same dimensions might be doable.

Can you confirm that it works if your crop the image down to 1.5 GB? 

Best,
Robert

**Comment by krizzodil** [comment]
[cl_info.txt](https://github.com/clij/clij2/files/5713016/cl_info.txt)
![gauss2D](https://user-images.githubusercontent.com/63590534/102561856-053d1400-40d6-11eb-8dd9-62a8e916fe36.PNG)

I wrote a script to test different NSlices. It only started to work once it was down to 0.7 GB. You can find the script and output in the screenshot. The radius of the gauss didn't change the success, only the processing time.
Best wishes,
Christian

**Comment by haesleinhuepf** [comment]
Glad that you figured out how to make it work. Just two minor comments: 
* After calling clij2.clear() you don't need to close images. That's what clij2.clear does for you.
* Real performance comes from calling multiple processing steps in a row while not releasing and reallocating memory. See this exercise for details:
https://github.com/clesperanto/i2k2020_tutorial_clij_clesperanto/blob/master/exercise11_reuse_memory.md

May I close this issue? 🙃

**Comment by krizzodil** [comment]
Ah, I understand! Builtin splitting of input-data would not be a favor to the user, as this would cost a lot of performance decrease when processing multiple steps. (Though, in case of the GUI it might be interesting. Yet, in turn, it would create a discrepancy between GUI-calls and scripting-calls).
Unfortunately I missed the opportunity to register for your I2K workshop, and many others. I'm still hoping for recordings ;)

Yes, the issue, especially in my head, is closed.

Liebe Grüße,
& schöne Feiertage,
Christian

**Comment by krizzodil** [comment]
Oh, and thank you so much for your time!
And my apologies for opening a rather unnessesary issue!
