### ISSUE TITLE
CLIJx-Assistant

### ISSUE THREAD

**Issue by ky395** [clij/clij2#29]
I'm trying to segment my image using the Top Hat Box filter (and some others). I tried to change the radius but nothing seems to change in the image? Why?
Also does red mean it's still processing and when its done the box turns green? 
It didn't do anything with the big image so I tried to crop a small one (29MB) still the same.
![image](https://user-images.githubusercontent.com/48921796/108637988-16e6c300-745b-11eb-9e69-8556be0aac46.png)

**Comment by haesleinhuepf** [comment]
Hi @ky395 ,

I just tried with your screenshot. I upsampled it to 4000x4000 pixels and ran the top-hat filter. Your screenshot also looks like it was able to compute the result at least once: the right image appears background-subtracted indeed.
![image](https://user-images.githubusercontent.com/12660498/108638422-765ec600-748f-11eb-9cd4-60dde7b9dc72.png)

On my Intel-GPU it just takes a second. Thus, I'm not sure why the window stays red in your case. Was there a console window popping up with an error message? If not, can you restart Fiji and try again?

Let me know if this helps!

Cheers,
Robert

**Comment by ky395** [comment]
It works! Also works on my whole image crop! Thanks!
