### ISSUE TITLE
IJM Markdown

### ISSUE THREAD

**Issue by ky395** [clij/clij2#30]
Hi Robert,
I like your IJM Markdown option. Running this on a different computer but I do not see this option. How do I get this option to show?

Thank you.
![Picture1](https://user-images.githubusercontent.com/48921796/108779446-e5422a80-7534-11eb-8968-45305ecaf845.png)

**Comment by haesleinhuepf** [comment]
Hi @ky395 ,

in order to use imagej-macro-markdown, you just need to install it as described on its [website](https://github.com/haesleinhuepf/imagejmacromarkdown) by activating the "IJMMD" update site in Fiji.

Cheers,
Robert
