### ISSUE TITLE
Switching the CL-Device while the assistant is running makes it crash.

### ISSUE THREAD

**Issue by piango** [clij/clij2#32]
Hi 

Great tool, clij.
Just getting used to it. Amazing

I started using it, but I get these error messages when I via the 'clij assistant':
- Filter(noise removal) --> Gaussian Blur3D(CLIJ2)
- Transform --> Make Isotropic
- Transform --> Rigid Transform
- Transform --> also a few others but not all

Attached is an example of error I get for 'Gaussian Blur3D(CLIJ2)' .
<img width="995" alt="clij_error" src="https://user-images.githubusercontent.com/46752563/110475641-6bd43b80-80e1-11eb-9643-cc661bc94b1f.PNG">

I am using the graphics card of my windows laptop
<img width="159" alt="GPU" src="https://user-images.githubusercontent.com/46752563/110475938-bb1a6c00-80e1-11eb-9cc4-8a5eb67eff52.PNG">

Hope its something easy. And not so silly from my side. :)  :)

**Comment by haesleinhuepf** [comment]
Hey @piango ,

great to see you here! Not so great that you get this error message :-)

I'm a tiny bit confused: The 1050 Ti GPU should be absolutely be able to process this 23 MB image. However, the error message says in the top right corner, that the image is stored on an "Intel(R)... " GPU.

Could you just try again? Please start the GPU memory display before starting the assistant and watch what's happening. You can also switch between different GPUs by clicking the menu `Plugins > ImageJ on GPU (CLIJx) > Change Default CL Device`

Also: How is the pixel-size of your data set? That could be relevant when using the makeIsotropic function.

Cheers,
Robert

**Comment by piango** [comment]
I will close this issue as a satisfied customer
;)

**Comment by haesleinhuepf** [comment]
> Some features of Clij don't work with Intel Graphics card. I guess.

No! Everything works fine on Intel. But if you push images to the Intel GPU and then change the GPU used, the images are not pulled over. I reopen and rename this issue to take care of it. Thanks for reporting this bug!

**Comment by haesleinhuepf** [comment]
I've added a warning message to the dialog to prevent that happening again :-)
![image](https://user-images.githubusercontent.com/12660498/111027626-a562ba80-83f1-11eb-8660-f720ae7dd8f8.png)
