### ISSUE TITLE
connectedComponentsLabeling - Diamond yields Box results

### ISSUE THREAD

**Issue by pdd2110** [clij/clij2#37]
Howdy!

Just a heads up - I was playing around with the connectedComponentsLabeling algorithms yesterday and noticed that the Diamond and Box algorithms both yielded the Box result. This was true for all of the different functions in CLIJ (CLIJ2, CLIJx, etc.). I'm assuming both are running the same code.

**Comment by haesleinhuepf** [comment]
Hey @pdd2110 ,

good catch. I can confirm this bug. Just for the record, when executing this macro, it becomes obvious:
```
test_image = newArray(0, 1, 0,
                      1, 0, 0,
                      1, 0, 1)

run("CLIJ2 Macro Extensions", "cl_device=");
Ext.CLIJ2_pushArray(source, test_image, 3, 3, 1);
Ext.CLIJ2_connectedComponentsLabelingBox(source, box_destination);
Ext.CLIJ2_connectedComponentsLabelingDiamond(source, diamond_destination);
print("Box:");
Ext.CLIJ2_print(box_destination);
print("Diamond:");
Ext.CLIJ2_print(diamond_destination);
```

**Comment by haesleinhuepf** [comment]
Thanks again for reporting this bug. I just fixed it. In case you need a fix urgently, feel free to try this replacement jar:
[clij2_-2.2.0.25-hotfix-ccl.jar.zip](https://github.com/clij/clij2/files/6291440/clij2_-2.2.0.25-hotfix-ccl.jar.zip)

If you would find a minute to confirm that the bug is fixed in this jar, that woudl be awesome.

Thanks again for the report!

**Comment by pdd2110** [comment]
Thanks a ton Robert, I’ll test it out tomorrow!

Sent from iPhone

On Apr 11, 2021, at 05:12, Robert Haase ***@***.***> wrote:

﻿

Thanks again for reporting this bug. I just fixed it. In case you need a fix urgently, feel free to try this replacement jar:
clij2_-2.2.0.25-hotfix-ccl.jar.zip<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_clij_clij2_files_6291440_clij2-5F-2D2.2.0.25-2Dhotfix-2Dccl.jar.zip&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=QIb03IehesAvgrQsNb5W_DqTcLUW75lvLg77-OBaeD4&m=N4O9xbRLI-ea1070GZUU1UsWOIynUlJzPfHhba_W5OY&s=SUV_qurwomjqX-mIogxoj3AO2g5NalXuASMn0k9Odww&e=>

If you would find a minute to confirm that the bug is fixed in this jar, that woudl be awesome.

Thanks again for the report!
