### ISSUE TITLE
Only able to install via updating fiji

### ISSUE THREAD

**Issue by spoonboi1** [clij/clij2#47]
You can only install it by going through the update fiji menu which automatically updates fiji when you open it, but updating fiji breaks something i need to use it for...

**Comment by haesleinhuepf** [comment]
Hi @spoonboi1 ,

you can install updates without downloading all files by selecting "Keep as is" in the plugin you do not want to update:
![image](https://user-images.githubusercontent.com/12660498/148664343-b40ab4bd-7efd-4405-b96d-f0e89859fbf0.png)

Furthermore, did you tell developers of the "something" that it breaks in recent Fiji updates?

Let me know if this helps!

Best,
Robert
