### ISSUE TITLE
Projections do not maintain voxel size metadata

### ISSUE THREAD

**Issue by tischi** [clij/clij2#50]
See title! Could this be changed? I think is quite an issue for using this in practice.
cc @manerotoni

**Comment by haesleinhuepf** [comment]
Just a quick comment: Clij operations (called from macro, jython, etc) never copy any metadata. The Clij assistant only copies metadata if input image and output image have the same size (which is already a bit speculative but works OK in practice). Hence, if you can think of a logic how pixel sizes can be copied from input to output images, I think that's possible.

**Comment by tischi** [comment]
> Hence, if you can think of a logic how pixel sizes can be copied from input to output images, I think that's possible.

For projections that logic is obvious, isn't it?

**Comment by haesleinhuepf** [comment]
I'm just leaving a link here to the CLIJ FAQ before closing this:
https://clij.github.io/clij-docs/faq.html#physical_units
