### ISSUE TITLE
GetBoundingBox returns incorrect values if binary image not 0 1

### ISSUE THREAD

**Issue by schmiedc** [clij/clij2#56]
https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/plugins/GetBoundingBox.java

The output bounding box values are multiplied by the value of the binary object. 
For instance 0 1 will get: 
X: 426
Y: 675
Z: 1
W: 951
H: 997
D: 73

With a binary image 0 2:
X: 852
Y: 1350
Z: 2
W: 1901
H: 1993
D: 145

and so on... Tried to find out where this happens. But could not understand it.

**Comment by haesleinhuepf** [comment]
> Tried to find out where this happens. But could not understand it.

I presume the issue sits somewhere here:
https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/plugins/BoundingBox.java#L41

I guess a similar issue like #54

**Comment by schmiedc** [comment]
I looked again. You multiply the image values with the coordinates first: 
https://github.com/clij/clij2/blob/a13ebc54863d56c5866e4343844764e5cc63cb0c/src/main/java/net/haesleinhuepf/clij2/plugins/MultiplyImageAndCoordinate.java#L40

Maybe convert the image here into a 0 1 binary before feeding into the multiplication, at the level of BoundingBox.java?

**Comment by haesleinhuepf** [comment]
Hi @schmiedc ,

yes, I think that's the solution, similar to the change you did in the other PR.

Again, if you send a PR, cool. Otherwise, I'll do it soonish.

Thanks!
Robert

**Comment by schmiedc** [comment]
Hi @haesleinhuepf 

I can do a PR sure :) 

I complain, I fix.

**Comment by schmiedc** [comment]
@haesleinhuepf 

here you go **https://github.com/clij/clij2/pull/57**

**Comment by haesleinhuepf** [comment]
Fixed in #57 

Thanks @schmiedc !
